#!/bin/bash
#
#  run_h2_server -- This script starts the H2 DB server with all necessary jar files.
#  It should be run in the directory containing the MDBC code.
#

POM=pom-h2server.xml

if [ ! -f $POM ]
then
	echo mk_jboss_module: Where is $POM?
	exit 1
fi

mvn -f $POM -Dmaven.test.skip=true install
if [ $? != 0 ]
then
	echo mk_jboss_module: maven failed...
	exit 1
fi

export CLASSPATH=$( mvn -f $POM dependency:build-classpath | grep -v INFO )
echo CLASSPATH is:
echo $CLASSPATH | tr : '\012'

cd /tmp
java org.h2.tools.Server
